server:
  port: 8081

spring:
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: group-sachet
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 3

product.config:
  profile: default
  serverUrl: https://dummyjson.com/products
  skipStart: 0
  skipLimit: 194
  productCallCron: 0 */1 * * * ?
  databaseConfiguration:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommproduct
    userName: root
    password: hawking101@
    connectionTimeOut: 50000
    maxLifeTime: 1800000
    maxPoolSize: 5
    poolName: product-db