server:
  port: 8080

spring:
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      bootstrap-servers: kafka-0.kafka-svc.default.svc.cluster.local:9094,kafka-1.kafka-svc.default.svc.cluster.local:9094,kafka-2.kafka-svc.default.svc.cluster.local:9094
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 3

product.config:
  profile: default
  serverUrl: https://dummyjson.com/products
  skipStart: 0
  skipLimit: 194
  productCallCron: 0 */1 * * * ?
  databaseConfiguration:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local:3306/ecommproduct
    userName: sachet
    password: hawking101@
    connectionTimeOut: 50000
    maxLifeTime: 1800000
    maxPoolSize: 5
    poolName: product-db